# Generated by Django 4.2.6 on 2024-01-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kitob nomi')),
                ('books_author', models.CharField(max_length=50, verbose_name='Muallifi')),
                ('price', models.IntegerField(verbose_name='Narxi')),
            ],
        ),
    ]
