# Generated by Django 4.2.6 on 2024-01-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0007_customer_product_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loyiha10.customer'),
            preserve_default=False,
        ),
    ]
