# Generated by Django 4.2.6 on 2024-01-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0008_category_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
