# Generated by Django 4.2.6 on 2024-01-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0017_remove_customer_age_remove_customer_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customers',
            field=models.ManyToManyField(through='loyiha10.Purchase', to='loyiha10.customer'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
