# Generated by Django 4.2.6 on 2024-01-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0003_alter_books_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dob',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='books',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='User Id'),
            preserve_default=False,
        ),
    ]
