# Generated by Django 4.2.6 on 2024-01-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0004_delete_dob_delete_news_books_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='Id')),
                ('name', models.CharField(max_length=50, verbose_name='Kategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Maxsulot nomi')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('total', models.IntegerField(verbose_name='Soni')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyiha10.category')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loyiha10.category'),
            preserve_default=False,
        ),
    ]
