# Generated by Django 4.2.6 on 2024-01-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0005_category_product_books_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
