# Generated by Django 4.2.6 on 2024-01-22 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0006_remove_category_user_id_delete_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ism')),
                ('l_name', models.CharField(max_length=30, verbose_name='Familiyasi')),
                ('age', models.IntegerField(verbose_name='Yoshi')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loyiha10.customer'),
            preserve_default=False,
        ),
    ]
