# Generated by Django 4.2.6 on 2024-01-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0009_rename_name_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='customer_id',
        ),
    ]
