# Generated by Django 4.2.6 on 2024-01-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0011_customer_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='category_id',
        ),
    ]
