# Generated by Django 4.2.6 on 2024-01-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0014_remove_category_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='prise',
        ),
    ]
