# Generated by Django 4.2.6 on 2024-01-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0018_product_customers_alter_purchase_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customers',
        ),
    ]
