# Generated by Django 4.2.6 on 2024-01-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0021_remove_product_user_id_product_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
