# Generated by Django 4.2.6 on 2024-01-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0023_rename_customer_name_product_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='data',
            new_name='date',
        ),
    ]
