# Generated by Django 4.2.6 on 2024-01-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0024_rename_data_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
