# Generated by Django 4.2.6 on 2024-01-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0025_alter_product_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='create_time',
        ),
    ]
