# Generated by Django 4.2.6 on 2024-01-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0026_rename_date_product_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loyiha10.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='delete_day',
            field=models.IntegerField(default=1, verbose_name='Yaroqlilik muddati'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ishlab chiqarilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=100, verbose_name='Maxsulot nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Narhi'),
        ),
    ]
