# Generated by Django 4.2.6 on 2024-01-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha10', '0002_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Kitob ', 'verbose_name_plural': 'Kitoblar '},
        ),
    ]
