# Generated by Django 5.0.1 on 2024-01-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_admin_category_customer_items_product_shopcart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcart',
            old_name='customer_id',
            new_name='customer_name',
        ),
    ]
