# Generated by Django 5.0.1 on 2024-01-27 17:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_purchasehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='items_id',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.timezone)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
